### ISSUE TITLE
Acceptance tests deleted

### ISSUE THREAD

**Issue by timiyay** [abuiles/ember-watson#103]
I just ran `ember-watson` on my Ember 2.7.0 codebase for the first time, and it rocks! Hooking it up to CodeClimate now...

I had to revert watson's changes to my acceptance tests, assumedly caused by the `destroyApp` change: https://github.com/abuiles/ember-watson#tests-use-destroy-app-helper

The end result was that my acceptance test files were emptied, getting rid of all of my test code, and replacing it with a single line

```
import { module, test } from 'qunit';
```

The workaround was to `git reset` changes to any file in `tests/acceptance`

**Comment by abuiles** [comment]
pinging @tim-evans

**Comment by tim-evans** [comment]
Oh man. I thought I caught all these. Will look at this in the am

**Comment by tim-evans** [comment]
Did you use --dry-run?

**Comment by tim-evans** [comment]
Oh and for good measure, what version are you running? The current published version of ember-watson doesn't have `--dry-run` on it.

**Comment by timiyay** [comment]
@tim-evans no, I didn't use `--dry-run`. I ran `ember help` and looked for a `--dry-run` flag, but didn't see it there.

I installed with `ember install ember-watson`, so I'm on the latest published version.

It's not mad urgent. Let me know if there's any debug output you'd like me to dig up and post, if you can't find a repro.

**Comment by abuiles** [comment]
@tim-evans @timiyay I just published  0.8.3 which includes --dry-run.

@tim-evans sorry about my delay publishing this, I added you as a collaborator on NPM :), just in case I block you again in the future.

**Comment by tim-evans** [comment]
No blocking me here. I just got a pit in my stomach when I was pinged. Like... oops. Did I mess something up? Haha

**Comment by timiyay** [comment]
I upgraded to 0.8.3 and ran `ember watson:all --dry-run`, which showed some output I didn't quite understand:

```
{ filename: 'tests/acceptance/map/property-test.js' } '\u0000'
{ filename: 'tests/acceptance/map-test.js' } '\u0000'
{ filename: 'tests/acceptance/pro-signup-test.js' } '\u0000'
{ filename: 'tests/unit/controllers/map/property-test.js' } '\u0000'
```

It appears to be saying "I'm going to do something to these 4 files", but I don't know what `\u0000` indicates.

When I ran it for reals, I had the same problem as originally reported - the contents of my acceptance test files were emptied, and replaced with a single line:

```js
import {module, test} from 'qunit';
```

**Comment by knownasilya** [comment]
Looks like the result is printed next to the filename, and in this case `\u0000` means NULL.

**Comment by knownasilya** [comment]
Ping @tim-evans

**Comment by tim-evans** [comment]
@knownasilya humm. That output is for CodeClimate as null terminators

**Comment by timiyay** [comment]
Closing this issue I opened, as I'm not currently using this addon, and the issue is stale.
