### ISSUE TITLE
Check for duplicate keys when converting needs to inject

### ISSUE THREAD

**Issue by code0100fun** [abuiles/ember-watson#104]
When running `ember watson:replace-needs-with-injection`on a controller that looks like:

```
export default Em.Controller.extend({
  needs: ['foo'],
  fooController: Em.computed.alias('controllers.foo')
});
```

the command currently generates:

```
export default Em.Controller.extend({
  fooController: Em.inject.controller('foo'),
  fooController: Em.computed.alias('fooController')
});
```

I think the output should be:

```
export default Em.Controller.extend({
  fooController: Em.inject.controller('foo')
});
```

I can understand not wanting to remove keys but I think it's a safe bet with such a specific collision. If it guesses wrong then it's easy enough to recover from source control.

Any thoughts before I try to implement this?

**Comment by knownasilya** [comment]
Go for it, if you still want to 👍
