### ISSUE TITLE
new command: replace ES6 destructuring assignment  & core classes references via root `Ember` namespace with ember-cli-shims

### ISSUE THREAD

**Issue by msalahz** [abuiles/ember-watson#109]
Hi, According to [ember-cli-shims](https://github.com/ember-cli/ember-cli-shims#why) readme :
Historically, Ember has recommended that developers reference core classes 
& utilities (ie `Component`, `Route`, `isEmpty`) via the root `Ember` namespace. 
This leads to the entire `Ember` module being imported into nearly every file:

```js
import Ember from 'ember';

export default Ember.Component.extend({
  foo: Ember.inject.service(),
  bar: Ember.computed.readOnly('foo.bar')
});
```

It would be preferable to have different parts of Ember available as separate modules, 
allowing developers to only import what they need. This is the direction the framework 
is moving in, but the modules are not yet available. This has led to a common pattern of 
ES6 destructuring assignment to enable writing future-proof code:

```js
import Ember from 'ember';

const { Component, computed, inject } = Ember;

export default Component.extend({
  foo: inject.service(),
  bar: computed.readOnly('foo.bar');
});
```

However, [ember-cli-shims](https://github.com/ember-cli/ember-cli-shims#why) library provides shims to mimic the future modules that Ember may provide, 
enabling developers to avoid destructuring and instead import the namespaces as modules *today*.

```js
import Component from 'ember-component';
import computed from 'ember-computed';
import injectService from 'ember-service/inject';

export default Component.extend({
  foo: injectService(),
  bar: computed.readOnly('foo.bar');
});
```

That way, as true modules become available in the Ember ecosystem, we can merely remove 
the shims from `ECS` upstream, requiring little to no refactoring on the part of 
developers who have opted-in to this pattern early. Ultimately, the goal of this 
library is to be replaced completely once Ember itself is an npm package/addon and exports its own modules.

**So, I would like to propose supporting a new command as `ember watson:replace-ember-namespaces-ref-and-dest-with-shims`.**

It should replace all ES6 destructuring assignment  & core classes references via root `Ember` namespace with import statements, as it specified above :
> expected input

```js
import Ember from 'ember';

const { Component, computed } = Ember;

export default Component.extend({
  foo: Ember.inject.service(),
  bar: computed.readOnly('foo.bar');
});
```
> expected output 

```js
import Component from 'ember-component';
import computed from 'ember-computed';
import injectService from 'ember-service/inject';

export default Component.extend({
  foo: injectService(),
  bar: computed.readOnly('foo.bar');
});
```

**Comment by msalahz** [comment]
Here is an ember cli shims [cheatsheet](https://gist.github.com/msalahz/25c1d77255d014251a7725d9c2abf0a9#file-ember-cli-shims-cheatsheet-md) I created manually and there is a PR will be pushed soon to automate generating it and include it in ember-cli-shims readme

**Comment by blimmer** [comment]
First of all, thank you for opening this issue - this was a big question for me and my team as we look forward to moving to the new structured modules.

One question though, does this work belong in the [modules codemod](https://github.com/tomdale/ember-modules-codemod) that Tom noted in the [original RFC](https://github.com/emberjs/rfcs/pull/176/files)?

The readme [specifically calls out that it doesn't work with destructing `Ember`](https://github.com/tomdale/ember-modules-codemod#known-issues).

**Comment by knownasilya** [comment]
I didn't think that the official shims had converted to the new RFC structure. Last I knew, only https://github.com/DockYard/ember-new-modules-shim had the new structure.

**Comment by msalahz** [comment]
No @blimmer I didn't know about it before, but I think its a very good start.
The current ember-cli-shims modules support importing modules like this
```
import Component from 'ember-component';
import { or } from 'ember-computed';
```
and new modules will look like this
```
import Component from "@ember/component";
import { or } from "@ember/object/computed"
```
@knownasilya new modules support in ember-cli-shims is coming soon in the following  [PR](https://github.com/ember-cli/ember-cli-shims/pull/92)

So my plan is  replace ES6 destructuring assignment & core classes references via root `Ember` namespace based on ember-cli-shims version installed in the project regardless its using old or new modules with consideration for upgrading from old to new Modules Shim. What you think ?

**Comment by msalahz** [comment]
Hi, I'm closing this in favor of [ember-modules-codemod](https://github.com/tomdale/ember-modules-codemod)
