### ISSUE TITLE
Can't process file with destructuring assignment

### ISSUE THREAD

**Issue by Soliah** [abuiles/ember-watson#30]
Given something like this:

```
actions: {
  foo: function() {
    Ember.RSVP.all([promise1, promise2]).then(([result1, result2]) => {});
  }
}
```

I get the standard "I wasn't able to save..." files message from watson.

**Comment by abuiles** [comment]
@Soliah which command were you running? do you have a file which is all commented ?

**Comment by Soliah** [comment]
Ah it was the function prototype removal command. Wasn't a commented file but when I commented out the part with destructuring it worked fine.

**Comment by abuiles** [comment]
@Soliah awesome! I know recast goes nuts when the whole file is commented, I'll check if we can do something.
