### ISSUE TITLE
Add async:false to all Ember.Data belongsTo/hasMany in beta

### ISSUE THREAD

**Issue by igorT** [abuiles/ember-watson#40]
https://github.com/emberjs/data/issues/3220

**Comment by Serabe** [comment]
I'll give it a try this evening.

**Comment by abuiles** [comment]
@Serabe did you have time to check this out?

**Comment by Serabe** [comment]
I started, but had a really long day at work and couldn’t get much code done. I have a few node scripts that I think correctly checks whether the relationship has the async or not (mostly based on the other formulas) but need to clean it up an start writing some tests.

On 12 Jun 2015 at 11:14:01, Adolfo Builes (notifications@github.com) wrote:

@Serabe did you have time to check this out?

**Comment by abuiles** [comment]
Closed by #41
