### ISSUE TITLE
idea: rename model

### ISSUE THREAD

**Issue by samselikoff** [abuiles/ember-watson#44]
Would be great to have a command to rename a model

**Comment by trabus** [comment]
@samselikoff would this fulfill what you're asking for? https://github.com/ember-cli/rfcs/pull/17

**Comment by samselikoff** [comment]
This would let you rename 'foo-model' to 'bar-model', and fix all references everywhere?

**Comment by trabus** [comment]
Yes, however the fixing references part isn't quite right yet. It's a little too greedy and is currently affecting references that aren't actually references to the model. Still, if you're interested you can try it out with `ember install ember-cli-rename`

**Comment by samselikoff** [comment]
Ok but it sounds like that project is solving this problem, so I'll go
ahead and close this.
