### ISSUE TITLE
Providing explanations and additional resources

### ISSUE THREAD

**Issue by mattmcmanus** [abuiles/ember-watson#51]
This may not be a real 'issue' but I thought it was worth posting some feedback. I'm about 2 months developing my first ember app full time. I've tried to keep up with all the changes that are coming down the line for 2.0 and for the most part most things are clear. 

The two new tasks that were recently added to this library, `convert-ember-data-model-lookups` and `convert-ember-data-async-false-relationships`, have confounded me though. I've read the docs and dug around and can't find anything explaining why these changes *should* be made.

Would it possible to provide info (a link would be fine) explaining, for example, why all model lookups should be dasherized and the ramifications of making/not making the change?

ember-watson is just part of the puzzle. There is so much dust being kicked up with all of the changes in ember at the moment it's hard to know whats going on sometimes

**Comment by abuiles** [comment]
@mattmcmanus thanks! that's a great idea, I just added this in the latest command https://github.com/abuiles/ember-watson/commit/bab73023d8f45b1ef01c0b93e85c7a27861cc471#diff-04c6e90faac2675aa89e2176d2eec7d8R83  

Want to contrib with the other ones :) ?

**Comment by mattmcmanus** [comment]
Thanks! I'll see what I can add. Thanks for the nudge. 

The ember-data 1.13 blog post explained A LOT as well.
