### ISSUE TITLE
ember watson:convert-ember-data-async-false-relationships not finding models ?

### ISSUE THREAD

**Issue by justin-hackin** [abuiles/ember-watson#64]
The documentation is ambiguous as to whether or not I need to specify the directory of my models, I assumed it would know they are in app/models.  However, when I used app/models/* as a parameter, I get the following message:

```
Oh Dear! I wasn't able to save the following files:
app/models/area-layer.coffee

A possible cause is having all the source code commented.
If that's not the problem please fill a report with the hospital directors
at https://github.com/abuiles/ember-watson/issues.
```

All the source code is definitely not commented.  It's a pretty simple model so I'll post it here:
```
`import DS from 'ember-data'`
###*
 * Represents an area layer i.e. suite, which can be displayed in an asset region, styled with layerStyles, and can present area info 
 * @class AreaLayer
 * @namespace Models
###
AreaLayer = DS.Model.extend {
  ###*
   * Name of layer
   * @property layerName
  ###
  layerName:DS.attr('string') # req'd
  ###*
   * Area of layer (units defined in Models.BuildingInfo)
   * @property area
  ###
  area:DS.attr('number') # req'd
  floor: DS.belongsTo('floor')
}

`export default AreaLayer`
```

This would suggest that using without a parameter is not attempting to doctor my models, and that there's something wrong with watson or my use of it.  None of my other models have changed from the looks of my git diff.  Any insights would be appreciated.

**Comment by justin-hackin** [comment]
Also, I removed the '# req'd' comment after the code and that didn't help

**Comment by fivetanley** [comment]
Ember Watson doesn't work on coffeescript files, sorry. :(
