### ISSUE TITLE
ember-watson commands included in production bundle

### ISSUE THREAD

**Issue by mattmcmanus** [abuiles/ember-watson#65]
In trying to debug some other issue on my production deploy, I found what looks like to be all of the command definitions in my vendor bundle. 

```
define("ember-watson/commands/index", function() {
    "use strict";
    module.exports = {
        "watson:upgrade-qunit-tests": require("./upgrade-qunit-tests"),
        "watson:convert-prototype-extensions": require("./convert-prototype-extensions"),
        "watson:convert-ember-data-model-lookups": require("./convert-ember-data-model-lookups"),
        "watson:convert-ember-data-async-false-relationships": require("./convert-ember-data-async-false-relationships"),
        "watson:convert-resource-router-mapping": require("./convert-resource-router-mapping")
    }
}), define("ember-watson/commands/upgrade-qunit-tests", function() {
    "use strict";
    var e = require("../../index"), t = new e;
    module.exports = {
        name: "watson:upgrade-qunit-tests",
        description: "Fix QUnit tests to match 2.0 syntax.",
        works: "insideProject",
        anonymousOptions: ["<path>"],
        run: function(e, r) {
            var n = r[0] || "tests";
            t.transformQUnitTest(n)
        }
    }
})
```

and so on. I'm not familiar with how the addon system handles development code from production, but is it possible to not compile this into the bundle?

**Comment by marcioj** [comment]
Good catch! #67 should fix your issue.
Thanks for report!

**Comment by mattmcmanus** [comment]
Hooray! I helped!

On Sun, Jul 26, 2015 at 8:09 PM Marcio Junior <notifications@github.com>
wrote:

> Good catch! #67 <https://github.com/abuiles/ember-watson/pull/67> should
> fix your issue.
> Thanks for report!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/abuiles/ember-watson/issues/65#issuecomment-125050905>
> .
>
-- 

*Matt McManus*
Independent Developer, Designer & Technical Advocate
(215) 565-5379
http://mcmanus.io
