### ISSUE TITLE
convert-resource-router-mapping

### ISSUE THREAD

**Issue by SamvelRaja** [abuiles/ember-watson#79]
While converting the resource router mapping

```bash
Oh Dear! I wasn't able to save the following files:
app/router.js - Cannot read property 'arguments' of undefined
```
My router structure is

```js
Router.map(function () {
  this.resource('items', function () {
    this.resource('item_details', {
      path: '/:item_id'
    }, function () {
      if (AdminUser) {
        this.route('create_subitem', {
          path: '/new_sub_item'
        });
      }
    });
  });
});

export default Router;
```

But if i **remove**    `if (AdminUser)`  check, it works.

Is this a know scenario? or needs a fix.

My use case is for certain routes i won't let the staff persons, hence i won't create a route for them at all, resulting them to take the unauthorized route by default.

**Comment by knownasilya** [comment]
Usually that's not the way you block routes, it's usually done in the `beforeModel` hook of the routes you want to auth.

**Comment by SamvelRaja** [comment]
@knownasilya  :+1:  will follow that. TY.

**Comment by SamvelRaja** [comment]
But this [PR](https://github.com/abuiles/ember-watson/pull/80) fixed my problem without removing the `if statement`

**Comment by marcioj** [comment]
This pattern isn't a good practice, but I think the formula should not crash if there is an `if` or other expressions inside the router
