### ISSUE TITLE
Add task to remove prototype extensions

### ISSUE THREAD

**Issue by tim-evans** [abuiles/ember-watson#8]
Since this seems to becoming the default, having a task to remove decorators that use prototypes would be really nice :3

See:
https://github.com/ember-cli/ember-cli/pull/3645
https://github.com/emberjs/guides/pull/110

**Comment by stefanpenner** [comment]
ya good idea, this should be a relatively simple transformation.

**Comment by kamal** [comment]
I pushed a PR to transform CP and observers https://github.com/abuiles/ember-watson/pull/10

Next steps would be to transform more prototype extensions like

```javascript
'hello %@'.fmt('world')
```

Is there a complete list somewhere?

**Comment by tim-evans** [comment]
@kamal I think fmt should be removed and quasi literals are used. But that's up to the core team.

**Comment by stefanpenner** [comment]
@tim-evans I would be on board with that. If someone opens an issue I'll bring it up this next meeting for discussion

**Comment by tim-evans** [comment]
@stefanpenner woot

**Comment by abuiles** [comment]
Just released the new command thanks to @kamal!

```
npm install ember-watson@0.2.0 --save-dev
ember convert-prototype-extensions
```

**Comment by abuiles** [comment]
Actually leaving open until we have figured how to transform other parts of the extensions.

**Comment by tim-evans** [comment]
Supporting `on` would be nice too :)
