### ISSUE TITLE
How do I disable a command for cI?

### ISSUE THREAD

**Issue by shicholas** [abuiles/ember-watson#95]
I am trying to use the ember-watson engine on Code Climate with mocha and cannot figure out how to disable the upgrade-qunit check. Is there a way to do this programmatically? I'd be happy to document it if so.

Thank you,

**Comment by abuiles** [comment]
@shicholas hey Nick, I don't think we have a way to do this at the moment, but it could be done maybe with a config var and then picking up here https://github.com/abuiles/ember-watson/blob/master/lib/commands/index.js#L3 only the commands we are interested in. 

This is not something I plan to work on, but I'm most that happy to code review if you go ahead with it.

**Comment by shicholas** [comment]
thanks for your answer @abuiles, I feel that I can get most of out of this library if I enable everything so I changed my code to just that.

thanks again for your work!
